[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/auth/tiktok/*"
  to = "/.netlify/functions/auth-tiktok/:splat"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
